### ISSUE TITLE
Australian phone number beginning with 0460 not recognised as valid

### ISSUE THREAD

**Issue by hennersreed** [twcclegg/libphonenumber-csharp#100]
Hi,

A customer using our system has a real Australian phone number (Telstra) in the format +614600xxxxx, but this is not recognised as valid by libphonenumber. I think this range may have been recently added in AU. Can this please be fixed?

Thanks,
Henry

**Comment by hennersreed** [comment]
Thanks for a great library by the way.

**Comment by twcclegg** [comment]
Have you checked http://libphonenumber.appspot.com? eg http://libphonenumber.appspot.com/phonenumberparser?number=%2B61460012345. See [here](https://github.com/twcclegg/libphonenumber-csharp/blob/master/CONTRIBUTING.md).
If it's a Google metadata issue, once reported to them it is usually fixed by the next release, they are about every two weeks. This library usually has releases in about a day after the Google version.

**Comment by hennersreed** [comment]
Thanks for the advice - very useful URL. The URL above also returns IsValid = false for the phone number in question - I guess I'll wait for Google to update their metadata.

**Comment by twcclegg** [comment]
You can leave a message on https://groups.google.com/forum/#!forum/libphonenumber-discuss if you want to make sure they're aware of the change.

**Comment by Silic0nS0ldier** [comment]
It seems highly likely the issue described here is upstream as twcclegg has pointed out. I experienced this problem in https://github.com/jackocnr/intl-tel-input which uses the same library to power validation. One of the most recent patch releases (somewhere after v16.0.0 and confirmed from v16.0.8) fixed the issue. It seems probable that these patch releases included the upstream updates.
