### ISSUE TITLE
[Feature Request] Phone number only for spesific country

### ISSUE THREAD

**Issue by albilaga** [twcclegg/libphonenumber-csharp#106]
This feature is for who using this lib and considering the size. A little background, I am building Xamarin.Forms app and using this lib for phone number validation. This lib working great but the size in my Android showing for raw file size for 13.3 MB and I am using this lib only for validating 1 country. With this feature hopefully when user just using 1 country it can reduce the file size. 
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/2399099/61965781-458c8580-affb-11e9-829b-ccbc2450e8f1.png">

**Comment by twcclegg** [comment]
I'm not sure that that would be very feasible that would be. The majority of the data is the geocoding data rather than the basic phone number validity metadata. Splitting that out might be possible. Also to better parity the Java version the source data ideally should be serialized to binary however I haven't found time to complete that task.
Per Xamarin if you plan to also target iOS note that validation is much, much slower due to the lack of compiled regexes.

**Comment by albilaga** [comment]
I see. Thats why in iOS sometimes it laggy for the first time. Anyway do I need to close this or just let it open? I hope maybe in the future it will be implemented and it will be great
