### ISSUE TITLE
Dot instead of space after country code

### ISSUE THREAD

**Issue by tomaszChmury** [twcclegg/libphonenumber-csharp#107]
Hi.
Is this possible to format number to have dot instead of space after country code?
I mean: +48.12 345 67 89 instead of +48 12 345 67 89
Thank you

**Comment by twcclegg** [comment]
This library intends to be parity of Google's libphonenumber https://github.com/google/libphonenumber, see http://libphonenumber.appspot.com/phonenumberparser?number=%2B48123456789 for demo. You could in theory ask them for such a feature, otherwise you will need to find some sort of workaround if you need that formatting.
