### ISSUE TITLE
Can't compile with VS 2019

### ISSUE THREAD

**Issue by wizofaus** [twcclegg/libphonenumber-csharp#120]
Get a bunch of weird errors including

...\github\libphonenumber-csharp\csharp\PhoneNumbers\PhoneNumbers.csproj : error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.

but I was able to re-create a csproj file that worked fine:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="1.7.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\resources\**" />
  </ItemGroup>

</Project>
```

**Comment by twcclegg** [comment]
The library targets several versions, `net35;net40;net46;netstandard1.3;netstandard2.0;portable-net45+win8+wpa81+wp8` in order to build the solution as is you need to install two components into Visual Studio: .NET Portable Library targeting pack and .NET Framework 3.5 development tools. Once that is done run `xcopy "C:\Program Files (x86)\MSBuild\Microsoft\Portable" "C:\Program Files\dotnet\sdk\$(dotnet --version)\Microsoft\Portable\" /S /E` (from [here](https://github.com/twcclegg/libphonenumber-csharp/blob/master/appveyor.yml#L22)) this likely will require powershell to be run as admin.
Alternatively when working locally, you can just remove all the frameworks except for netstandard2.0, which then allows for cross-platform development.

**Comment by wizofaus** [comment]
Hmm, ok, that wasn't entirely obvious from the build instructions.  Is there no way you can have a csproj file that will work even without the targeting pack and .NET 3.5 development tools installed?  Anyway you can close this.

**Comment by twcclegg** [comment]
I'll add a blurb to the README on building. Both targets are comparatively new to the library.

**Comment by twcclegg** [comment]
Also I'll mull over if there is a good way to have a second sln with a second csproj or something for development. Not settled on a best method for that yet.
