### ISSUE TITLE
Relax System.Collections.Immutable version constraint

### ISSUE THREAD

**Issue by cmeeren** [twcclegg/libphonenumber-csharp#129]
I assume there is no reason why libphonenumber-csharp must require `System.Collections.Immutable >= 5.0.0`. This is causing issues with other packages I am referencing, which require `>= 1.5.0 && < 2.0.0` (itself too restrictive, but I'll raise a separate issue for that on the relevant repo).

I suggest releasing a new version of libphonenumber-csharp that allows older versions of `System.Collections.Immutable`, like before.

**Comment by twcclegg** [comment]
It was updated from 1.7.0 to attempt to resolve https://github.com/twcclegg/libphonenumber-csharp/issues/124, I can drop it back to 1.7.1 in the next release. That might be longer than usual since Google tends to do an end of year code freeze, in the meantime you can use https://ci.appveyor.com/api/buildjobs/ykw6vujbk98f2lm2/artifacts/csharp%2FPhoneNumbers%2Fbin%2FRelease%2Flibphonenumber-csharp.8.12.14-eb2cf55.nupkg

**Comment by cmeeren** [comment]
> That might be longer than usual since Google tends to do an end of year code freeze

I don't understand; surely there is no problem releasing a new NuGet version even though the Google lib has no changes?

**Comment by twcclegg** [comment]
If it really causes an issue I could put out a 8.12.15-pre or 8.12.14.1 or something, but the NuGet version is pinned to the Google metadata version.

**Comment by cmeeren** [comment]
I see. No worries, I can use the previous libphonenumber-csharp version until then.

Version pinning to external dependencies can cause a few such devops headaches, yes. :) I have found it is much better not to do it, allowing me to make improvements and release new versions of my libraries separately from the source.
