### ISSUE TITLE
Some Uruguay phones numbers are returned invalid

### ISSUE THREAD

**Issue by sahik11** [twcclegg/libphonenumber-csharp#137]
I am using v8.12.27

There are some Uruguay phone numbers that are resulting invalid but these are valid numbers,  Please find attached images below.

Examples
+598 1770 2000 : US embassy
+598 1987 0000 : CitiGroup 

[https://uy.usembassy.gov/](url)
[https://aplicaciones.anp.com.uy/montevideo/autoridades.asp](url)

![1](https://user-images.githubusercontent.com/30450637/128065511-133d88fd-9a81-4d3e-9592-8b42948e4b8a.JPG)
![image](https://user-images.githubusercontent.com/30450637/128066248-81e93754-fd4f-4a4e-9502-06cfa562cc7e.png)

**Comment by twcclegg** [comment]
The same result shows here https://libphonenumber.appspot.com/phonenumberparser?number=%2B598+1987+0000 please open the issue with Google https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue

**Comment by hajrasaubhik** [comment]
@twcclegg The issue with Uruguay phone numbers are fixed by Google in the DLL release version of 8.12.36 and the current latest version of the DLL released by Google is 8.12.38. But the latest NuGet available is still 8.12.34. Could you please let us know when will you be releasing the NuGet packages pointing to the latest DLLs from Google as we are waiting for this to upgrade the package in our project.

**Comment by twcclegg** [comment]
I neglected to update this issue but the metadata has now been updated and released many times.
