### ISSUE TITLE
How to parse without getting exception for wrong format?

### ISSUE THREAD

**Issue by ziaulhasanhamim** [twcclegg/libphonenumber-csharp#160]
I'm getting a phone number input from the user. So I try to parse it using the `Parse` method of `PhoneNumberUtil`. If the number format is incorrect then it will throw an exception. But I don't want to get an exception. I want something like `TryParse` which will return a boolean containing success or failure. Is there an easy to achieve this behavior?

**Comment by twcclegg** [comment]
This port tries to parity Google's Java version and as such doesn't have some patterns more common to C# e.g. TryParse.
Probably the best and simplest would be just wrapping Parse with a try/catch block.

**Comment by ziaulhasanhamim** [comment]
Adding TryParse is no harm after all it's a useful method that most C# developers gonna look for. Like there isn't a need of changing anything in the port itself. TryParse will do the same thing returning false for failure instead of throwing exceptions.

**Comment by brolaugh** [comment]
Adding `TryParse` to the library is a slippery slope to adding more things that isn't strictly 1-to-1 with Google's Java version. 
It will lead to questions like:

> You added the `TryParse` method so why not add the `FooBar` method as well?

**Comment by ziaulhasanhamim** [comment]
> You added the TryParse method so why not add the FooBar method as well?

There is nothing wrong with adding FooBar also if it makes the developer experience better.

But yeah I can understand that thing strict port. Like the API should be one to one with java version

**Comment by angelaki** [comment]
How about just creating an extension method, if you need it?

```
    public static bool TryParse(this PhoneNumbers.PhoneNumberUtil util, string numberToParse, string defaultRegion, out PhoneNumbers.PhoneNumber? phonenumber)
    {
        phonenumber = null;

        try { phonenumber = util.Parse(numberToParse, defaultRegion); return true; }
        catch { return false; }
    }
```

**Comment by twcclegg** [comment]
Would you like a libphonenumber-csharp.extensions package with that functionality? I would need to ponder what other functionality it might contain, but should be straightforward enough to make happen.

**Comment by ziaulhasanhamim** [comment]
That would be great to have.

**Comment by twcclegg** [comment]
Okay I'll look into it, almost all of the effort is on the logistics side, CI and nuget changes; not any actual code changes.

**Comment by twcclegg** [comment]
Should there be `TryParse` and `TryParseValid` maybe?

**Comment by twcclegg** [comment]
Feel free to give https://www.nuget.org/packages/libphonenumber-csharp.extensions/8.13.2-alpha1 a shot, any comments or review of #164 is welcome.

**Comment by darko1979** [comment]
Sorry for posting in old thread.

I think that most of you missed the point of having TryParse and that is to avoid exceptions where they are not necessary because they are expensive on performance.
Everybody knows how to write a helper function to wrap original Parse function into TryParse but that does not remove problem with exeptions.

Look at this small example using int.Parse and int.TryParse.
If we use BenchmarkDotNet to test the performance of these methods when they are successful or when they fail,
we can see why you should use TryParse if you do not care why method failed.

```cs
        [Benchmark]
        public int Test_ParseValid()
        {
            try { return int.Parse("12345"); } catch { return 0; }
        }
        [Benchmark]
        public int Test_TryParseValid()
        {
            return int.TryParse("12345", out var result) ? result : 0;
        }

        [Benchmark]
        public int Test_ParseInvalid()
        {
            try { return int.Parse("1234a"); } catch { return 0; }
        }
        [Benchmark]
        public int Test_TryParseInvalid()
        {
            return int.TryParse("1234a", out var result) ? result : 0;
        }
```

Running this code on .NET 8.0 gives following result:

| Method               | Mean          | Error       | StdDev      | Gen0   | Allocated |
|--------------------- |--------------:|------------:|------------:|-------:|----------:|
| Test_ParseValid      |      8.971 ns |   0.1706 ns |   0.1513 ns |      - |         - |
| Test_TryParseValid   |      8.756 ns |   0.1064 ns |   0.0889 ns |      - |         - |
| Test_ParseInvalid    |  5,851.192 ns |  69.2724 ns |  61.4082 ns | 0.0763 |     504 B |
| Test_TryParseInvalid |     11.113 ns |   0.0780 ns |   0.0651 ns |      - |         - |

.NET 9.0 fixed some performance on exceptions but still it is a huge difference using two methods:

| Method               | Mean          | Error       | StdDev     | Gen0   | Allocated |
|--------------------- |--------------:|------------:|-----------:|-------:|----------:|
| Test_ParseValid      |      8.207 ns |   0.1938 ns |  0.1813 ns |      - |         - |
| Test_TryParseValid   |      7.681 ns |   0.0573 ns |  0.0508 ns |      - |         - |
| Test_ParseInvalid    |  2,835.134 ns |  55.6643 ns | 49.3449 ns | 0.0763 |     480 B |
| Test_TryParseInvalid |      9.864 ns |   0.0576 ns |  0.0539 ns |      - |         - |

I think that TryParse should be main function that returns parsed result and error (if there is any),
and Parse should just call TryParse and throw an exception when error happens.

**Comment by twcclegg** [comment]
I agree with most all of the above in principle however note that the PhoneNumbers library only supports functionality that is in the Google's libphonenumber. Other functionality that people have asked for over the years is in the extensions library.
