### ISSUE TITLE
American phone not correctly parsed? 

### ISSUE THREAD

**Issue by jkone27** [twcclegg/libphonenumber-csharp#211]
this phone 
`00113476208000`

was parsed as

+1 and `3476208000`
instead of
+1 and `13476208000`

not clear why as the prefix is correctly inferred, but one '1' is lost?

```fsharp
#r "nuget:libphonenumber-csharp"
open PhoneNumbers

let PhoneParser = PhoneNumberUtil.GetInstance()

let phone = PhoneParser.Parse("00113476208000", "NL")

printfn $"+{phone.CountryCode} {phone.NationalNumber}"

printfn $"""{phone.CountryCode = 1} {phone.NationalNumber = 13476208000UL}"""

printfn $"""is wrong national numnber without 1 at the beginning? {phone.NationalNumber = 3476208000UL}"""

 ```
 
 and results
 ```
+1 3476208000
True False
is wrong national numnber without 1 at the beginning? True
 ```

**Comment by twcclegg** [comment]
National number does not include country code, within NANPA that means just area code and number.
NationalNumber is public due to the nature of protobuf and that this library is port from Google's Java version.
You're better off using PhoneNumberUtil.Format() which includes options of National, International, E.164, RFC3966
This can test behavior here https://libphonenumber.appspot.com/phonenumberparser?number=%2B13476208000

**Comment by jkone27** [comment]
my bad actually we found that indeed the input was wrong, thank you for checking this anyways! :)
