### ISSUE TITLE
PhoneNumberUtil.GetInstance() Is taking too much time.

### ISSUE THREAD

**Issue by AwsomeCode** [twcclegg/libphonenumber-csharp#38]
Hi 
I am using lib for Web App. Which is hosted via IIS. If IIS is idle for some time(No request are coming) it will start GC and after if any new request comes "PhoneNumberUtil.GetInstance()" will take 2 to 3 sec to re initialize. Can It be optimize some how? 

Thanks.

**Comment by kinosang** [comment]
use Dependency Injection with `.AddSingleton<IPhoneNumberParser>(new PhoneNumberParser())` instead of use `PhoneNumberUtil.GetInstance()` directly.

FYI, this project does not provide the interface and service, you should create them by yourself.

**Comment by AwsomeCode** [comment]
Thanks I will tried it out.

**Comment by adrianknight89** [comment]
@AwsomeCode Did you figure this out? It's taking quite long for me as well.

**Comment by twcclegg** [comment]
If I get the porting the binary serialization code working, it should speed up initialization time, and decrease package size, etc. https://github.com/twcclegg/libphonenumber-csharp/pull/45

**Comment by adrianknight89** [comment]
@twcclegg Thanks. I have noticed that while `PhoneNumberUtil.GetInstance()` takes long to initialize, another long runner is calling `InputDigit()` on the `AsYouTypeFormatter` for the first time. I wanted to use this library in Xamarin Forms to validate mobile numbers during account signup, but when the user hits a digit on the soft keyboard for the first time, there is a noticeable delay for that digit, especially on iOS.

Do you expect the porting to be done anytime soon? I saw #45 was opened in 2017.

**Comment by kinosang** [comment]
> @twcclegg Thanks. I have noticed that while `PhoneNumberUtil.GetInstance()` takes long to initialize, another long runner is calling `InputDigit()` on the `AsYouTypeFormatter` for the first time. I wanted to use this library in Xamarin Forms to validate mobile numbers during account signup, but when the user hits a digit on the soft keyboard for the first time, there is a noticeable delay for that digit, especially on iOS.
> 
> Do you expect the porting to be done anytime soon? I saw #45 was opened in 2017.

@adrianknight89 I don't think validate user input on the client side is a good idea.

BTW, I'm waiting #45 to be done too, I use DI and singleton interface to "speed up" the library now, it speed time and grab memory when the application startup.

**Comment by adrianknight89** [comment]
@kinosang I do input validation on both client and server sides. I did try holding a reference to a `PhoneNumberUtil` after the application starts and using it on the input validation page. This helps reduce time, but it doesn't help with `AsYouTypeFormatter`, especially on iOS. 

I then fed random digits into the type formatter again after app start so that the formatter doesn't need to be cold init on the validation page. This fixed lagging completely on Android, but it didn't improve anything on iOS.

**Comment by twcclegg** [comment]
Yeah I'd like to figure out a way to split up #45, it been difficult to get all the data to serialized and deserialize correctly and is also implementing other missing features . As for `AsYouTypeFormatter` slow on iOS, I think that's just going to be the way things are since it lacks compiled regexs.
