### ISSUE TITLE
[8.8.3] PhoneNumberUtil.Parse(string numberToParse, string defaultRegion) returns duplicate CountryCodes

### ISSUE THREAD

**Issue by gitegite** [twcclegg/libphonenumber-csharp#43]
numberToParse = "61 (2) 22333"
defaultRegion = "AU" 

It returns 6161222333 instead of the expected 61222333.

The older version 7.7.5 works fine.

**Comment by twcclegg** [comment]
I'm unable to reproduce, how are you getting the output, also http://libphonenumber.appspot.com/ shows it as not being a valid number

**Comment by gitegite** [comment]
Thanks for your reply.

I ran the case on my unit test using this function `PhoneNumberUtil.Parse(string numberToParse, string defaultRegion)` and debug it for the output. The result shows that it is not valid too.

So, I switch to version 7.7.4 using Nuget manager and the test passes.

Maybe you can try to target http://libphonenumber.appspot.com/ to an older version, says 7.7.4, and test it?

**Comment by twcclegg** [comment]
The appspot demo is owned and maintained by Google and thus not something I can modify.
I tried copying the 7.7.4 metadata into the csharp port and it still shows your sample number as invalid, also note that 7.7.4 is almost a year old.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia says NSN should be 9 digits rather than the six in your example.
However, if you still think this behavior is incorrect I suggest you file an issue with https://github.com/googlei18n/libphonenumber since they maintain the metadata the defines which numbers are considered possible and valid, this repo merely attempts to duplicate that functionality for .NET

**Comment by gitegite** [comment]
I have discussed with the team and concluded that 6 digits for Australia should not be valid.

Thanks for your support!
