### ISSUE TITLE
Verify takes an instance of PhoneNumberUtil

### ISSUE THREAD

**Issue by wallymathieu** [twcclegg/libphonenumber-csharp#74]
```c#
var _util = PhoneNumberUtil.GetInstance();
var result = _util.Verify(PhoneNumberUtil.Leniency.VALID, number, str, _util);
```
Is the intent for this to be:
```c#
var _util = PhoneNumberUtil.GetInstance();
var result = PhoneNumberUtil.Verify(PhoneNumberUtil.Leniency.VALID, number, str, _util);
```
or
```c#
var _util = PhoneNumberUtil.GetInstance();
var result = _util.Verify(PhoneNumberUtil.Leniency.VALID, number, str);
```
?

**Comment by twcclegg** [comment]
I believe it will require you to do the latter since it is not a static function https://github.com/twcclegg/libphonenumber-csharp/blob/master/csharp/PhoneNumbers/PhoneNumberUtil.cs#L485. This code predates my ownership of this port. It's a bit of a strange situation due the way in which java does enums https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L477. It does make make for a silly, redundant signature.

**Comment by wallymathieu** [comment]
Aaa, so then the correct port would be to:
```c#
public static class LeniencyExtensions{
   public static bool Verify(this Leniency leniency, PhoneNumber number, string candidate, PhoneNumberUtil util){
     // ...
  }
}
```
since that could add a method to an enum
