### ISSUE TITLE
Fail on lowercase county code

### ISSUE THREAD

**Issue by Cozidian** [twcclegg/libphonenumber-csharp#92]
Country code in lowercase fails and it should not. 
Problem:
```
 var phoneNumberUtil = PhoneNumbers.PhoneNumberUtil.GetInstance();
 var nationalPhoneNumber = "2024561111";
 phoneNumber = phoneNumberUtil.Parse(nationalPhoneNumber, "us");
```
Got an error.
---------------
Possible Solution:
`countryCodeQueryString.ToUpper();`

**Comment by brolaugh** [comment]
Although I can't find anyone mentioning the usage of upper case vs lower case in ISO 3166 (which the country codes derive from) all documents I've used all have their country codes uppercase. 
Although I haven't read the ISO 3166 document it self (as I don't feel like paying $40 in order to do so) I do believe that it specifies that country codes should be upper case because of the reason above.

**Comment by twcclegg** [comment]
Without digging in to ISO 3166, http://libphonenumber.appspot.com/phonenumberparser?number=2024561111&country=us returns `Error type: INVALID_COUNTRY_CODE. Missing or invalid default region.` I do note that if you fill in "us" to http://libphonenumber.appspot.com/ it takes you to http://libphonenumber.appspot.com/phonenumberparser?number=2024561111&country=US. Given that it would seen uppercase is required.
