### ISSUE TITLE
Impermissible size of library

### ISSUE THREAD

**Issue by VictorKochetkov** [twcclegg/libphonenumber-csharp#98]
I would like to use this library in Xamarin app, but the size of Nuget is about 11 MB! Why?
That makes this library not useful in mobile development.

**Comment by twcclegg** [comment]
It due to that it include https://github.com/twcclegg/libphonenumber-csharp/tree/master/resources/geocoding which is sizeable, however it currently targets 5 frameworks: net35, net40, netstandard1.3, netstandard2.0, and portable-net45+win8+wp8+wpa81 meaning each is a 1/5 of the nupkg.
This library however is generally this app is not good for mobile because it is slow because portable doesn't support compiled regexes (https://github.com/twcclegg/libphonenumber-csharp/blob/master/csharp/PhoneNumbers/InternalRegexOptions.cs)

**Comment by dwfrancis** [comment]
Suggest re-opening this. Each target DLL is ~= 13.5 MB. The entire nuget package compresses all three into a total size of 14.5 MB.

Framework 4.6+, Standard and Core/5+ support zipped streams so we can compress the geocoding data and reduce the dll size to ~= 4.5 MB

See PR #147
